# Generated by Django 4.2.7 on 2023-11-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
