# Generated by Django 4.2.7 on 2024-07-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_reset_token_customuser_timestamp_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='timestamp_field',
            new_name='reset_token_created_at',
        ),
    ]
