# Generated by Django 4.2.7 on 2024-07-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_timestamp_field_customuser_reset_token_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIcons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
