# Generated by Django 4.2.7 on 2024-07-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profileicons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='icon',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_icon_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profileicons'),
        ),
    ]
