# Generated by Django 4.2.7 on 2024-07-08 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_customuser_icon_customuser_profile_icon_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileIcons',
            new_name='ProfileIcon',
        ),
    ]
