# Generated by Django 4.2.7 on 2024-07-15 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavedRoute',
            new_name='SavedRoutes',
        ),
    ]
