# Generated by Django 4.2.7 on 2024-07-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saved_routes', '0005_rename_savedroutes_savedroute'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroute',
            name='distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedroute',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
